[Enhancement] Thumb Size
jsuarezruiz/TemplateUI pull request #15
Opened 2020-10-12 17:53 UTC by dimonovdd

What do you think about it?
<img src="https://user-images.githubusercontent.com/59065470/95776348-cef5a980-0ccc-11eb-8a3b-9192dc0730db.png" width="177" height="384"/>

2020-10-12 19:31 UTC, dimonovdd commented
We also need to make the position of the thumb to be set through its center, not its left edge

2020-10-18 16:44 UTC, jsuarezruiz commented
Oh, here we have the first external contribution. Thanks!.

Mnn, what do you think if we simplify this option and have only one `ThumbSize` property?

To use it, we would use  `ThumbSize = "50"` or `ThumbSize = "24, 48"`.

2020-10-18 16:47 UTC, jsuarezruiz requested changes
Oh, here we have the first external contribution. Thanks!.

Mnn, what do you think if we simplify this option and have only one `ThumbSize` property?

To use it, we would use  `ThumbSize = "50"` or `ThumbSize = "24, 48"`.

About the CornerRadius option. Mnn, it makes sense because we are using a Frame to draw the Thumb, but if you need a specific shape, must use a modified ControlTemplate. What do you think if we leave this option out, and whoever wants to use it, just have to modify the ControlTemplate?

2020-10-18 18:47 UTC, dimonovdd commented
thaks, maybe this is a way?
```xml
<controls:Slider
    TrackSize="4"
    ThumbColor="DarkGreen"
    Minimum="0"
    MinimumTrackColor="LightGreen"
    Maximum="10"
    MaximumTrackColor="LightGreen"
    Value="2">
    <controls:Slider.Thumb>
        <BoxView BackgroundColor="Blue" HeightRequest="30" WidthRequest="30" CornerRadius="15"/>
    </controls:Slider.Thumb>
</controls:Slider>
```

2020-10-18 21:48 UTC, dimonovdd commented
![image](https://user-images.githubusercontent.com/59065470/96386595-c60d4800-11a4-11eb-8f88-8b162e6a4550.png)

2021-02-21 11:31 UTC, jsuarezruiz requested changes

2021-02-21 11:31 UTC, jsuarezruiz commented on src/TemplateUI/Controls/Slider/Slider.cs
> +
I will review the calculations, when moving to the right there is at the beginning a little jump to the left. 
![thumbsize](https://user-images.githubusercontent.com/6755973/108623715-b480c900-7440-11eb-9ca9-4a928ab5733b.gif)

2021-02-22 21:58 UTC, dimonovdd commented
@jsuarezruiz 
Thank you for watching this.
I fixed bugs on calculating slider value and thumb position.

2021-03-01 18:22 UTC, jsuarezruiz approved these changes

2021-03-01 18:22 UTC, merged